name: sho-Cart-deployment
on: 
  push: 
    branches:
       - main
    paths-ignore:
      - 'README.md'
      - 'charts/**'
      - 'Dockerfile'
      - 'images/**'
      - 'sonar-project.properties'

jobs:
  Building:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate random tag number
        id: version_step
        run: |
          echo "VERSION=${RANDOM}" >> $GITHUB_ENV 
          echo "::set-output name=VERSION::${RANDOM}"

      - name: Logging into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Build and Push Docker Image"
        env:
          USERNAME: healerkay
          IMAGE_NAME: shoe
        run: |
          docker build -t $USERNAME/$IMAGE_NAME:${{ env.VERSION }} .
          docker push $USERNAME/$IMAGE_NAME:${{ env.VERSION }}
  Deploying:
    runs-on: ubuntu-latest
    needs: Building

    steps:        

      - name: "Install kubectl"
        uses: azure/setup-kubectl@v3
        with: 
          version: "v1.19.3"
        id: "install-kubectl"

      - name: "Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: "Connect to the EKS Cluster"
        run: |
          aws eks update-kubeconfig --name cluster

      - name: "Install Helm"
        uses: azure/setup-helm@v4.2.0
        id: "install-helm"

      - name: "Deploy Application via Helm"
        run: |
          helm upgrade --install shopping ./shopping -f shopping/values.yaml \
            --set image.tag=${{ env.VERSION }} \
            --set replicaCount=3
            
       
  Notification:
    runs-on: ubuntu-latest
    needs: Deploying

    steps:
      - name: "Announce the Latest Deployment Version"
        uses: dawidd6/action-send-mail@v3
        with:
          username: taykeny94@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          subject: "New Docker Image Version for Shoe-cart Web App"
          to: "abatankehinde1999@gmail.com"
          from: Healer <taykeny94@gmail.com>
          body: "New image build version: ${{ needs.Docker-Image.outputs.VERSION }}"





  
      

      

      